source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.1'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 6.0.3'
# Use Puma as the app server
gem 'puma', '~> 4.1'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.7'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use Active Model has_secure_password
gem 'bcrypt', '~> 3.1.7'

# Use Active Storage variant
# gem 'image_processing', '~> 1.2'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.2', require: false

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
# gem 'rack-cors'

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i(mingw mswin x64_mingw jruby)

# imgurにpostで画像登録リクエスト送るために用意しています。
gem 'httpclient'

# 環境変数をプロジェクトで管理するために用意しています。
gem 'dotenv-rails'

# token生成用
gem 'jwt'

# レスポンス用jsonシリアライズ用
gem 'active_model_serializers'

# mysql用
gem 'mysql2'

# i18nで文字列の管理する他に用意しています。
gem 'rails-i18n'

# ページングのために用意しています。
gem 'kaminari'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: %i(mri mingw x64_mingw)

  # rspec-rails テスト用フレームワーク
  # 参考：https://github.com/rspec/rspec-rails#installation
  %w[rspec-core rspec-expectations rspec-mocks rspec-rails rspec-support].each do |lib|
  gem lib, git: "https://github.com/rspec/#{lib}.git", branch: 'master'
  end

  # binding:pryによるdebug用gem
  gem 'pry-byebug'
  gem 'pry'
  gem 'pry-rails'

  # ダミーデータ作成用gem
  gem 'faker'
end

group :development do
  gem 'listen', '~> 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
    # require: false をつけるとRailsアプリ内では呼ばれなくなる。
  gem 'rubocop', require: false
end

# FactoryBot
# 参考：https://qiita.com/at-946/items/aaff42e4a9c2e4dd58ed
group :test do
  gem 'factory_bot_rails'
  # テスト後にデーターベースをリセットしてくれる
  gem 'database_cleaner'
  # rspecの記載を楽にしてくれる
  gem "shoulda-matchers"
end
